version: '3.8'

services:
  nginx:
    build: ./requirements/nginx # Build from Dockerfile in /nginx
    container_name: nginx
    #restart: always
    ports:
      - "443:443" # Map port 443 on host to port 443 in container
    networks:
      - inception_network
    depends_on:
      - wordpress # Start NGINX only after Wordpress is running

  wordpress:
    build: ./requirements/wordpress # Build from Dockerfile in /wordpress
    container_name: wordpress
    #restart: always
    volumes:
      - wordpress_data:/var/www/html/wordpress #Persistant storage for WordPress files
    networks:
      - inception_network
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    depends_on:
      - mariadb # Start Wordpress only after MariaDB is running

  mariadb:
    build: ./requirements/mariadb # Build from Dockerfile in /mariadb
    container_name: mariadb
    #restart: always
    volumes:
      - mariadb_data:/var/lib/mysql # Persistent storage for MariaDB database
    networks:
      - inception_network
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

volumes:
  wordpress_data: # Volume for Wordpress files
  mariadb_data:  # Volume for MariaDB database

networks:
  inception_network:  # Network for container communication
